### ISSUE TITLE
Rain and snow are returned as None when neither is forecast

### ISSUE THREAD

**Issue by 10100011** [freekode/pyopenweathermap#16]
As of v0.2.0, if rain and snow are not forecast and are missing from the API response, they are returned as None when previously they were empty dictionaries; e.g.:

`WeatherReport(current=CurrentWeather(wind_gust=14.92, wind_bearing=140, rain=None, snow=None`

This causes a TypeError in the Home Assistant integration, requiring a None check - [something which is being questioned](https://github.com/home-assistant/core/pull/128799#discussion_r1807821694).

Seemingly related to two [earlier](https://github.com/freekode/pyopenweathermap/commit/a516505815f32ff3278454ae0daeb1cf3873f745) [commits](https://github.com/freekode/pyopenweathermap/commit/938f17a83bc13402d6bb3382b454964be57a0a89).

@freekode: what is the correct behaviour here?

**Comment by freekode** [comment]
I think I decided that way to clearly mark the situation when there is no information about rain, snow, visibility, etc.
You may set as you wish.
