### ISSUE TITLE
Create git tags

### ISSUE THREAD

**Issue by mweinelt** [freekode/pyopenweathermap#2]
Hi!

I would like to package pyopenweathermap into nixpkgs for using it with Home Assistant.

It would be super helpful if you could tag releases on Git, so we could fetch releases including tests from here. Tests are unfortunately not uploaded to PyPi, which is not a big deal if we can consume them from Git.

Is that something you could integrate into your release workflow?

Thanks!

**Comment by freekode** [comment]
Yes, sure. I will update the workflow
